[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"

[[context.staging.plugins]]
package = "netlify-plugin-cypress"
  [context.staging.plugins.inputs]
  record = true